service: random-number-generate

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/hello2.zip

functions:
  hello2:
    handler: com.serverless.Handler
    events:
      - http:
          path: ping
          method: get
